### ISSUE TITLE
EU Setup?

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#180]
What about EU specific changes?

i.e. I am thinking about adding an option to remove the tax-display (show only the shipping link) - as it looks like in Italy we shall not show that.

Would such an option make sense for Germany as well? Or should be better make a for EU-Setup :-) ?

Might be interesting, as there are some unified laws going on concerning online shopping in EU.

Are there any plans for that?

Do you know about similar projects like German Setup in the EU ?

**Comment by avstudnitz** [comment]
I like the idea of a european / international setup. In my opinion, it'd be the right next step for us. We'd need to add some more configurations (mostly tax-specific).
What are our options?
1. Extend GermanSetup, keep the name, just make it usable in more european countries
2. Rename it to EuropeanSetup, InternationalSetup or something like that
3. Make a fork and rename it there

I'd prefer option 3, although option 1 provides much better maintainability for changes made in GermanSetup.

As I am working on more country distributions like Magento DE, Magento AT and Magento CH, I am willing to do a bigger part of that.

**Comment by gfobe** [comment]
**Variant 1**
Pros:
- best maintainability
- well known name

Cons:
- possibly some uncertainty of the user (do I have the correct extension?)
- marketing more difficult (only German oder international?)

**Variant 2**
Pros:
- name suggest what module is for
- normal development with new name

Cons:
- partly lost of well known name GermanSetup
- some troubles when you want to update the existing GermanSetup module

**Variant 3**
Pros:
- keep GermanSetup module small
- it's easy to use names of GermanSetup and the international setup side by side. If sometimes the users only want to use the international setup because it's "better", the name of the international setup will be established
- both can participate of each other with help of pull request or sth. like this

Cons:
- more work to keep GermanSetup and the international setup "in sync" during development and let they both participate from each other

**Comment by therouv** [comment]
I'd vouch for option 1 mainly because of the following reasons:
- I think we already have the basic structures in GermanSetup to support other countries (e.g. for taxes, etc.)
- New features would be available for all countries at the release date and not step by step. I doubt that we are able to keep all repositories for all countries in sync or deliver updates in a timely fashion.
- Because of the point above: I think there is a better maintainability for the complete extension.

The name should be changed though. Kind of like "MageSetup" or sth. like that.

**Comment by avstudnitz** [comment]
Okay, as there seem to be no further (differing) opinions, I'd like to start to work on the (sub-)project today. 
I like the name "MageSetup" for the package. 
@therouv, could you create a new repository with the new name for that? For now until the release, we can of course use a branch of this repository ("mage-setup").

Once I started work, I can better identify the to-dos.

**Comment by therouv** [comment]
@avstudnitz Please see https://github.com/firegento/firegento-magesetup

**Comment by avstudnitz** [comment]
Thanks :-) Work has begun, will be ready to be tested soon.
