### ISSUE TITLE
Multiple store fronts Germany.

### ISSUE THREAD

**Issue by paales** [firegento/firegento-germansetup#98]
We are running multi-lingual shops which currently has a storefront for the Netherlands and for the UK. We are planning to expand to Germany (shop in German, special marketing guy in Germany, etc.).

I looked for several hours online to find something about the German law to start a webshop there, but that information is very hard to find for a non-german speaking guy.

I got a few questions about the module as I suspect it at least implements the minimum required by law.

> Activation and base configuration of Terms and Conditions

What does it do, does it add boilerplate terms and conditions, or does it do something special?

> Creation of standard CMS pages

Which pages are created, and which are required by law?

> Enhanced price rendering including VAT and shipping costs

As far as I understand, this is required by law, right?

> Automatic generation of meta information for products

This is just handy, has nothing to do with the requirements for a german shop right?

> Supports the German "Button Loesung"

Required since last month or something right?

> Creates a history of newsletter subscriber registrations and unregistrations 

Required or just handy?

Does the module do other things that are not described in english on the Magento Connect page?

**Comment by riconeitzel** [comment]
- **Activation and base configuration of Terms and Conditions**
  - What does it do, does it add boilerplate terms and conditions, or does it do something special?

Simply configures magento to use T&C and creates 2 T&C entries that link to corresponding static blocks. these static blocks are empty templates for "AGB" and "Widerrufsbelehrung" (T&C and Revocation)
- **Creation of standard CMS pages**
  - Which pages are created, and which are required by law?

Privacy-, Delivery- and Payment information, imprint (uses backend input fields to show imprint), T&C (links to static block), Revocation (links to static block) – all required by law.
- **Enhanced price rendering including VAT and shipping costs**
  - As far as I understand, this is required by law, right?

yes.
- **Automatic generation of meta information for products**
  - This is just handy, has nothing to do with the requirements for a german shop right?

that's just comfy stuff not required by law
- **Supports the German "Button Loesung"**
  - Required since last month or something right?

yes. 
- **Creates a history of newsletter subscriber registrations and unregistrations**
  - Required or just handy?

i'm not sure but i guess it's required as it has to do with privacy - and privacy is ALWAYS a big matter in german law suits!

**Does the module do other things that are not described in english on the Magento Connect page?**

yes, delivery cost taxes can be calculated based on products taxes (full or reduced TAX) - special to german law. auto config values for confirmations and tax setup.

**Comment by therouv** [comment]
> > Creates a history of newsletter subscriber registrations and unregistrations
> > Required or just handy?
> 
> i'm not sure but i guess it's required as it has to do with privacy - and privacy is ALWAYS a big matter in german law suits!

If a newsletter receiver complains about receiving a newsletter it's your obligation as a store owner in Germany to prove if and when a customer has been subscribed to your newsletter.

**Comment by paales** [comment]
Thanks for the detailed responses, really helps us a lot!
